apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
    component: database
    shop: lamborghini
data:
  database.name: "lamborghini_shop"
  database.port: "5432"

# Made with Bob
