apiVersion: v1
kind: Service
metadata:
  name: frontend-lamborghini
  labels:
    app: frontend-lamborghini
    component: ui
    shop: lamborghini
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: frontend-lamborghini

# Made with Bob
